# yaml-language-server: $schema=../schema.json
tokens:
  - addressOrDenom: "0x68AbCC37de2BEb083Cd6A549f64C3494Ea418BB7"
    chainName: arbitrum
    decimals: 18
    name: Ether
    standard: EvmHypNative
    symbol: ETH
  - addressOrDenom: "0x61F71B85762c8848083506da347969c58248f0c6"
    chainName: base
    decimals: 18
    name: Ether
    standard: EvmHypNative
    symbol: ETH
  - addressOrDenom: "0x96d4357EB200f230816811b4320259b2f9228D5c"
    chainName: optimism
    decimals: 18
    name: Ether
    standard: EvmHypNative
    symbol: ETH
  - addressOrDenom: "0x2BAc449691070F058Fdb0E738D1bE9175f8ec63d"
    chainName: ethereum
    decimals: 18
    name: Ether
    standard: EvmHypNative
    symbol: ETH
  - addressOrDenom: "0x6341d878A7f8D1872D8EA6f10e15E89692DC7cd7"
    chainName: tangle
    decimals: 18
    name: Ether
    standard: EvmHypSynthetic
    symbol: ETH
