# yaml-language-server: $schema=../schema.json
tokens:
  - addressOrDenom: "0xd5c9FCfF2f362E89538E92e8B6e677571E11C1e7"
    chainName: arbitrum
    collateralAddressOrDenom: "0xFa7F8980b0f1E64A2062791cc3b0871572f1F7f0"
    decimals: 18
    name: Uniswap
    standard: EvmHypCollateral
    symbol: UNI
  - addressOrDenom: "0x25Eb364cb96485c22eE70a6cfc60717F0C0b3380"
    chainName: optimism
    collateralAddressOrDenom: "0x6fd9d7AD17242c41f7131d257212c54A0e816691"
    decimals: 18
    name: Uniswap
    standard: EvmHypCollateral
    symbol: UNI
  - addressOrDenom: "0xa3E0920CAf0e2eDDDe54D49fFC1d82e1a23c9693"
    chainName: polygon
    collateralAddressOrDenom: "0xb33EaAd8d922B1083446DC23f610c2567fB5180f"
    decimals: 18
    name: Uniswap
    standard: EvmHypCollateral
    symbol: UNI
  - addressOrDenom: "0xC2450aa58A3ec477B04F2122c8101eE6bdcC3A82"
    chainName: tangle
    decimals: 18
    name: Uniswap
    standard: EvmHypSynthetic
    symbol: UNI
