# yaml-language-server: $schema=../schema.json
tokens:
  - addressOrDenom: "0x4139b8F1474FFd04EE15F86103EF53f8Fdb3d8D0"
    chainName: arbitrum
    collateralAddressOrDenom: "0xf3527ef8dE265eAa3716FB312c12847bFBA66Cef"
    decimals: 18
    name: USDX
    standard: EvmHypCollateral
    symbol: USDX
  - addressOrDenom: "0x21F16dB63F954E5C73e06757E0fe136f2BF91564"
    chainName: ethereum
    collateralAddressOrDenom: "0xf3527ef8dE265eAa3716FB312c12847bFBA66Cef"
    decimals: 18
    name: USDX
    standard: EvmHypCollateral
    symbol: USDX
  - addressOrDenom: "0x04667a82F593d55aa34CE38B204Ec0Fdc54cDe0C"
    chainName: tangle
    decimals: 18
    name: USDX
    standard: EvmHypSynthetic
    symbol: USDX
