# yaml-language-server: $schema=../schema.json
tokens:
  - addressOrDenom: "0xc80f2Bd6Bc9C74a6674bC0A0966e76a5eAC51Cf7"
    chainName: arbitrum
    collateralAddressOrDenom: "0x3647c54c4c2C65bC7a2D63c0Da2809B399DBBDC0"
    decimals: 18
    name: Solv BTC
    standard: EvmHypCollateral
    symbol: SolvBTC
  - addressOrDenom: "0x677952E2ff8c5Fb2F2455a84AC70208f4c3d7810"
    chainName: ethereum
    collateralAddressOrDenom: "0x7A56E1C57C7475CCf742a1832B028F0456652F97"
    decimals: 18
    name: Solv BTC
    standard: EvmHypCollateral
    symbol: SolvBTC
  - addressOrDenom: "0x223E7B1EAd79C6603a891D9e733FD5ADD1044dd1"
    chainName: tangle
    decimals: 18
    name: Solv BTC
    standard: EvmHypSynthetic
    symbol: SolvBTC
