# yaml-language-server: $schema=../schema.json
tokens:
  - addressOrDenom: "0x15BC1c8861def0e6605685bFEdF3A6456f068dBa"
    chainName: arbitrum
    collateralAddressOrDenom: "0xbc011A12Da28e8F0f528d9eE5E7039E22F91cf18"
    decimals: 18
    name: swETH
    standard: EvmHypCollateral
    symbol: swETH
  - addressOrDenom: "0xC5D0781702D9c7BCcdA04DF3F767F1058e753cd1"
    chainName: ethereum
    collateralAddressOrDenom: "0xf951E335afb289353dc249e82926178EaC7DEd78"
    decimals: 18
    name: swETH
    standard: EvmHypCollateral
    symbol: swETH
  - addressOrDenom: "0x28ce5Ab9E7b4B04f146E3Ca5E3cb87D7b07d5497"
    chainName: tangle
    decimals: 18
    name: swETH
    standard: EvmHypSynthetic
    symbol: swETH
