# yaml-language-server: $schema=../schema.json
tokens:
  - addressOrDenom: "0xd7405f4396a90cD6B1f11f172F08034dBd9265D8"
    chainName: arbitrum
    collateralAddressOrDenom: "0xaf88d065e77c8cC2239327C5EDb3A432268e5831"
    decimals: 6
    name: USD Coin
    standard: EvmHypCollateral
    symbol: USDC
  - addressOrDenom: "0xf041B44EE24B5358D0999076933675fF5baCa437"
    chainName: base
    collateralAddressOrDenom: "0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913"
    decimals: 6
    name: USD Coin
    standard: EvmHypCollateral
    symbol: USDC
  - addressOrDenom: "0x7A153C00352DCb87E11684ce504bfE4dC170acCb"
    chainName: optimism
    collateralAddressOrDenom: "0x0b2C639c533813f4Aa9D7837CAf62653d097Ff85"
    decimals: 6
    name: USD Coin
    standard: EvmHypCollateral
    symbol: USDC
  - addressOrDenom: "0xf041B44EE24B5358D0999076933675fF5baCa437"
    chainName: polygon
    collateralAddressOrDenom: "0x3c499c542cEF5E3811e1192ce70d8cC03d5c3359"
    decimals: 6
    name: USD Coin
    standard: EvmHypCollateral
    symbol: USDC
  - addressOrDenom: "0x3DBBB4fdC5725FF780E653FfC3Af427029C259F3"
    chainName: ethereum
    collateralAddressOrDenom: "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48"
    decimals: 6
    name: USD Coin
    standard: EvmHypCollateral
    symbol: USDC
  - addressOrDenom: "0x524322C9bF30137E12f86EFE74D1Cba05f4126Fa"
    chainName: tangle
    decimals: 6
    name: USD Coin
    standard: EvmHypSynthetic
    symbol: USDC
