# yaml-language-server: $schema=../schema.json
tokens:
  - addressOrDenom: "0x122c216D5379376413Fc7B547598AcD5268A57B4"
    chainName: arbitrum
    collateralAddressOrDenom: "0x346c574c56e1a4aaa8dc88cda8f7eb12b39947ab"
    decimals: 18
    name: SolvBTC Babylon
    standard: EvmHypCollateral
    symbol: SolvBTC.BBN
  - addressOrDenom: "0x96d4357EB200f230816811b4320259b2f9228D5c"
    chainName: ethereum
    collateralAddressOrDenom: "0xd9D920AA40f578ab794426F5C90F6C731D159DEf"
    decimals: 18
    name: SolvBTC Babylon
    standard: EvmHypCollateral
    symbol: SolvBTC.BBN
  - addressOrDenom: "0xF0120960A6D667460F21f88778cb5e44cb90Ac3d"
    chainName: tangle
    decimals: 18
    name: SolvBTC Babylon
    standard: EvmHypSynthetic
    symbol: SolvBTC.BBN
