# yaml-language-server: $schema=../schema.json
tokens:
  - addressOrDenom: "0x7CFc15E7fD3998B962D1FC137b64d10513c18097"
    chainName: arbitrum
    collateralAddressOrDenom: "0x2416092f143378750bb29b79eD961ab195CcEea5"
    decimals: 18
    name: Renzo Restaked ETH
    standard: EvmHypCollateral
    symbol: ezETH
  - addressOrDenom: "0xCa965b842699e16b367702310f50161e03eb2d27"
    chainName: base
    collateralAddressOrDenom: "0x2416092f143378750bb29b79eD961ab195CcEea5"
    decimals: 18
    name: Renzo Restaked ETH
    standard: EvmHypCollateral
    symbol: ezETH
  - addressOrDenom: "0xb794b059bDA36a01C3757693D4136162752e03C6"
    chainName: optimism
    collateralAddressOrDenom: "0x2416092f143378750bb29b79eD961ab195CcEea5"
    decimals: 18
    name: Renzo Restaked ETH
    standard: EvmHypCollateral
    symbol: ezETH
  - addressOrDenom: "0xea4866eD17f557c8E4D2fB93E705320522216145"
    chainName: ethereum
    collateralAddressOrDenom: "0xbf5495Efe5DB9ce00f80364C8B423567e58d2110"
    decimals: 18
    name: Renzo Restaked ETH
    standard: EvmHypCollateral
    symbol: ezETH
  - addressOrDenom: "0x536889B3c998D36911BA73411F502662B0754684"
    chainName: tangle
    decimals: 18
    name: Renzo Restaked ETH
    standard: EvmHypSynthetic
    symbol: ezETH
