# yaml-language-server: $schema=../schema.json
tokens:
  - addressOrDenom: "0xD5B8441E2929e73f1e9a9C53b7a6863780897FFa"
    chainName: arbitrum
    collateralAddressOrDenom: "0xcbB7C0000aB88B473b1f5aFd9ef808440eed33Bf"
    decimals: 8
    name: Coinbase Wrapped BTC
    standard: EvmHypCollateral
    symbol: cbBTC
  - addressOrDenom: "0x07a4568A98621f90E7D94E87D7e9Bf806d5E19f3"
    chainName: base
    collateralAddressOrDenom: "0xcbB7C0000aB88B473b1f5aFd9ef808440eed33Bf"
    decimals: 8
    name: Coinbase Wrapped BTC
    standard: EvmHypCollateral
    symbol: cbBTC
  - addressOrDenom: "0x28db68252Ae4597cC4567d3C2A29Bc50D0BCA02d"
    chainName: ethereum
    collateralAddressOrDenom: "0xcbB7C0000aB88B473b1f5aFd9ef808440eed33Bf"
    decimals: 8
    name: Coinbase Wrapped BTC
    standard: EvmHypCollateral
    symbol: cbBTC
  - addressOrDenom: "0xFa0C5466EF2D1C6b4C769c8a3BaABD9e9107a6f7"
    chainName: tangle
    decimals: 8
    name: Coinbase Wrapped BTC
    standard: EvmHypSynthetic
    symbol: cbBTC
